###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Robert Mařík'
bibtex_bibfiles = ['references.bib']
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2022, 2023'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build', 'reseni*']
nb_execution_allow_errors = False
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_timeout = 30
extensions = [
    'sphinx_togglebutton', 
    'sphinx_copybutton', 
    'myst_nb', 
    'jupyter_book', 
    'sphinx_thebe', 
    'sphinx_comments', 
    'sphinx_external_toc', 
    'sphinx.ext.intersphinx', 
    'sphinx_design', 
    #'sphinx_book_theme', 
    'sphinx_proof', 
    'sphinxcontrib.bibtex', 
    'sphinx_jupyterbook_latex',
    'sphinx_last_updated_by_git'
    ]
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = ''
html_favicon = ''
html_logo = ''
html_show_copyright = False
html_sourcelink_suffix = ''
html_theme = 'sphinx_book_theme'
html_theme_options = {
    'extra_footer': '<p>\n<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>\n  All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>\n</p>',
    'announcement':'Toto je rozpracovaná verze učebního textu.','search_bar_text': 'Hledat v knize...',
    'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': 'https://mybinder.org', 'jupyterhub_url': 'https://jupyter.mendelu.cz', 'thebe': True, 'colab_url': 'https://colab.research.google.com'},
    'path_to_docs': '',
    'repository_url': 'https://github.com/robert-marik/dmp',
    'repository_branch': 'main',
    'google_analytics_id': '',
    'extra_navbar': '<a href="https://user.mendelu.cz/marik/dmp/Dynamicke_modely_populaci_text.pdf" style="width: 100%; margin: auto; border-top: solid; border-bottom: solid; display: block;">PDF verze</a><p>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>',
    'home_page_in_toc': False,
    'announcement': '',
    'use_repository_button': True,
    'use_edit_page_button': False,
    'use_issues_button': False
}
html_title = 'Dynamické modely populací'
nb_execution_cache_path = ''
nb_execution_mode = 'auto'
latex_engine = 'xelatex'
myst_enable_extensions = ['amsmath', 'dollarmath']
myst_url_schemes = ['mailto', 'http', 'https']
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = True
myst_dmath_double_inline = True

html_css_files = ['custom.css']
language = 'cs'
myst_footnote_transition = False
latex_elements = {
    'extrapackages': r'\usepackage{comment}', 
    'papersize': 'a4paper'
    }

html_js_files = [
    'https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js'
    'custom.js'
]

templates_path = ["_templates"]
